name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deployment:
    name: run deployment # A name for the deployment job
    runs-on: ubuntu-latest # The type of machine to run the job on
    environment: production # The deployment environment
    steps:
      - uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Build Project # Run a one-line script
        run: | # Generate static project
          echo "deploying..." 
          npm ci
          npm run build1
#      - name: Deploy to Hosting
#        uses: "appleboy/scp-action@v0.1.4" # Use the scp-action
#        with:
#          host: ${{ secrets.FIRSTVDS_HOST }} # The host address of the server you're deploying to
#          username: ${{ secrets.USERNAME }} # The username of the server you're deploying to
#          port: ${{ secrets.SSH_PORT }} # The port of the server you're deploying to
#          key: ${{ secrets.SSH_PRIVATE_KEY }} # The private key of the server you're deploying to
##          password: ${{ secrets.SSH_PASSWORD }}
#          source: "dist/." # The local directory you wish to copy to the server
#          target: "/var/www/meowmatrix.ru/public_html" # The remote directory you wish to copy to
#          strip_components: 2 # The number of directories to strip from the source path